#!/bin/bash

nohup python rainfallanomaly1_consumer.py &
echo "nohup python rainfallanomaly1_consumer.py &"
sudo nohup python3 heatmap_consumer.py &
echo "nohup python heatmap_consumer.py &"
nohup python rainfallanomaly2_consumer.py &
echo "nohup python rainfallanomaly2_consumer.py &" 
